language: swift
before_install:
  - cd Issue\ Manager
osx_image: xcode10
install: carthage bootstrap --platform iOS --no-build
script:
  - xcodebuild clean build -sdk iphonesimulator -project Issue\ Manager.xcodeproj/ -scheme Issue\ Manager CODE_SIGNING_REQUIRED=NO
