language: swift
osx_image: xcode10.1
before_install:
  - cd Issue\ Manager
install:
  - brew install git-lfs
  - git lfs install
  - git lfs version
  - carthage version
script:
  - carthage bootstrap --platform iOS --verbose && xcodebuild clean build -sdk iphonesimulator -project Issue\ Manager.xcodeproj/ -scheme Issue\ Manager CODE_SIGNING_REQUIRED=NO
  - sleep 10 # give logs time to catch up
after_failure:
  - echo '**** after failure called ****'
  - md5 Carthage/Checkouts/SimplePDFKit/SimplePDFKit/PDFium/libpdfium.a # sanity check
  - lipo -info Carthage/Checkouts/SimplePDFKit/SimplePDFKit/PDFium/libpdfium.a # sanity check
  - sleep 10 # give logs time to catch up
